### ISSUE TITLE
Can read /customers but not /customers/:id

### ISSUE THREAD

**Issue by teriiehina** [axabanque/API-Sample#2]
Hello dears AxaBanque engineers,

when I get the resource at /customers (providing my client_id and my access_token), I get a correct answer:

```
[{"customer":1}]
```

but when I try to reach /customers/1 (still using my credentials), I get 

```
{"error-detail":"access denied","error-code":"403","error":"access_denied"}
```

Poking around, I've found I can access customer-id 1000000, 1000001 and 1000002, which give respectively 

```
{"id":1000000,"label":"THEO"}
{"id":1000001,"label":"ANTONIN"}
{"id":1000002,"label":"LEA"}
```

My app name is fastaxa.
Regards.

**Comment by MathieuLorber** [comment]
For the moment you have to submit a customer_id GET parameter which will be later provided by the authentication mechanism (not by you...). The fact that you get a 200 response with /customers without submitting one is a side effect of this temporary mock. Customer id 1 does not exist : that's why trying to go further give you an error.

In fact, the existence of the id you submit in customer_id has no reason to be verified (since later it will come from a real authentication). That's why the /customers URL used with a non existing customer_id will respond [{"customer":{your id}] for the moment...

**Comment by teriiehina** [comment]
> For the moment you have to submit a customer_id GET parameter

you mean for the `/customers` or the `/customers/:customer-id` ?

How to know which values to give to the customer_id parameter ?

**Comment by agaudelas** [comment]
Okay I'll be taking this point right now...

 Actually there's a quick start guide to the API that mentions the hows and whys, but for some reason it hasn't been published yet. The basic idea is that on the live platform (the one that will ultimately provide you with real world data), you're connected with the authorization system that knows of the permissions the customer granted you. In the sandbox, there is no such system: your access token is actually checked against a set of existing apps, and that's it --in other words, auth is mocked. That is why you need to tell the sandbox which user you're querying for, and that's where the customer_id comes in. For short, here's the full list of available customers inside the sandbox:
1000000 
1000001 
1000002 
1500000

When querying the sandbox, just blindly add it in the following form: &customer_id={one of the above}

Again, this will be stated more clearly in the online documentation (hopefully by tomorrow). Sorry that it got you confused, and don't hesitate to come back if you have more questions.

**Comment by teriiehina** [comment]
okidoki, I get it now. Missing documentation is PITA ;)
nevertheless, thank you for answering this late, I may be able to play with your API now.

good luck with your challenge.
